FROM pcm32/galaxy-init-pheno

MAINTAINER PhenoMeNal-H2020 Project <phenomenal-h2020-users@googlegroups.com>

LABEL Description="Galaxy 17.05-phenomenal for running inside Kubernetes."
LABEL software="Galaxy Init"
LABEL software.version="17.05-pheno-lr"
LABEL version="1.3"

#COPY config/galaxy.ini config/galaxy.ini
COPY config/job_conf.xml config/job_conf.xml
COPY config/tool_conf.xml config/tool_conf.xml
COPY config/sanitize_whitelist.txt config/sanitize_whitelist.txt
COPY tools/phenomenal tools/phenomenal

COPY html/partners.png welcome/welcome_partners.png
COPY html/PhenoMeNal_logo.png welcome/welcome_PhenoMeNal_logo.png
COPY html/welcome.html welcome/welcome.html

COPY ansible ansible
COPY container-simple-checks.sh container-simple-checks.sh
COPY test_cmds.txt test_cmds.txt
